name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: CoverGo
          repo: CoverHealth-Automation
          github_token: ${{ secrets.PAT_TOKEN }}
          workflow_file_name: main.yml
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          sleep 10s
